version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - yum install -y curl
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - kubectl config set-cluster lts-stg --server=$server --certificate-authority=$sacacert
      - kubectl config set-credentials codepipeline --token=$satoken
      - kubectl config set-context codepipeline --cluster=lts-stg --user=codepipeline --namespace=staging
      - kubectl config use-context codepipeline
      - codebuild-breakpoint
      - ls /codebuild/output/src940293961/src
      - kubectl get pods -n staging

