version: 0.2

phases:
  install:
    commands:
      - yum install -y curl
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

  build:
    commands:
      - echo Build stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
     - echo $cacert > ca.crt
      - echo $client-key > admin.key
      - echo $client-cert > admin.crt
      - kubectl config set-cluster lts-stg --server=$api-server --certificate-authority=ca.crt
      - kubectl config set-credentials kube-admin-lts-stg --client-certificate=admin.crt  --client-key=admin.key
      - kubectl config set-context codepipeline --cluster=lts-stg --user=kube-admin-lts-stg 
      - kubectl config use-context codepipeline
      - kubectl version --insecure-skip-tls-verify
      - kubectl get pods -n staging --insecure-skip-tls-verify
